spring:
  application:
    name: course-service

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://192.168.50.190:2181
    group: local
  scan:
    base-packages: com.yong.course.service